// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: systemmanager.proto

package protobuf_msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemManagerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*SystemManagerMessage_ServiceDiscovery
	//	*SystemManagerMessage_TuningState
	Message isSystemManagerMessage_Message `protobuf_oneof:"message"`
}

func (x *SystemManagerMessage) Reset() {
	*x = SystemManagerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_systemmanager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemManagerMessage) ProtoMessage() {}

func (x *SystemManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_systemmanager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemManagerMessage.ProtoReflect.Descriptor instead.
func (*SystemManagerMessage) Descriptor() ([]byte, []int) {
	return file_systemmanager_proto_rawDescGZIP(), []int{0}
}

func (m *SystemManagerMessage) GetMessage() isSystemManagerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *SystemManagerMessage) GetServiceDiscovery() *ServiceDiscovery {
	if x, ok := x.GetMessage().(*SystemManagerMessage_ServiceDiscovery); ok {
		return x.ServiceDiscovery
	}
	return nil
}

func (x *SystemManagerMessage) GetTuningState() *TuningState {
	if x, ok := x.GetMessage().(*SystemManagerMessage_TuningState); ok {
		return x.TuningState
	}
	return nil
}

type isSystemManagerMessage_Message interface {
	isSystemManagerMessage_Message()
}

type SystemManagerMessage_ServiceDiscovery struct {
	ServiceDiscovery *ServiceDiscovery `protobuf:"bytes,1,opt,name=service_discovery,json=serviceDiscovery,proto3,oneof"`
}

type SystemManagerMessage_TuningState struct {
	TuningState *TuningState `protobuf:"bytes,2,opt,name=tuning_state,json=tuningState,proto3,oneof"`
}

func (*SystemManagerMessage_ServiceDiscovery) isSystemManagerMessage_Message() {}

func (*SystemManagerMessage_TuningState) isSystemManagerMessage_Message() {}

var File_systemmanager_proto protoreflect.FileDescriptor

var file_systemmanager_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f,
	0x6d, 0x73, 0x67, 0x73, 0x1a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x74, 0x75,
	0x6e, 0x69, 0x6e, 0x67, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb2, 0x01, 0x0a, 0x14, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4e, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x3f, 0x0a, 0x0c, 0x74, 0x75, 0x6e, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x54,
	0x75, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x75,
	0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_systemmanager_proto_rawDescOnce sync.Once
	file_systemmanager_proto_rawDescData = file_systemmanager_proto_rawDesc
)

func file_systemmanager_proto_rawDescGZIP() []byte {
	file_systemmanager_proto_rawDescOnce.Do(func() {
		file_systemmanager_proto_rawDescData = protoimpl.X.CompressGZIP(file_systemmanager_proto_rawDescData)
	})
	return file_systemmanager_proto_rawDescData
}

var file_systemmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_systemmanager_proto_goTypes = []interface{}{
	(*SystemManagerMessage)(nil), // 0: protobuf_msgs.SystemManagerMessage
	(*ServiceDiscovery)(nil),     // 1: protobuf_msgs.ServiceDiscovery
	(*TuningState)(nil),          // 2: protobuf_msgs.TuningState
}
var file_systemmanager_proto_depIdxs = []int32{
	1, // 0: protobuf_msgs.SystemManagerMessage.service_discovery:type_name -> protobuf_msgs.ServiceDiscovery
	2, // 1: protobuf_msgs.SystemManagerMessage.tuning_state:type_name -> protobuf_msgs.TuningState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_systemmanager_proto_init() }
func file_systemmanager_proto_init() {
	if File_systemmanager_proto != nil {
		return
	}
	file_servicediscovery_proto_init()
	file_tuningstate_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_systemmanager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemManagerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_systemmanager_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*SystemManagerMessage_ServiceDiscovery)(nil),
		(*SystemManagerMessage_TuningState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_systemmanager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_systemmanager_proto_goTypes,
		DependencyIndexes: file_systemmanager_proto_depIdxs,
		MessageInfos:      file_systemmanager_proto_msgTypes,
	}.Build()
	File_systemmanager_proto = out.File
	file_systemmanager_proto_rawDesc = nil
	file_systemmanager_proto_goTypes = nil
	file_systemmanager_proto_depIdxs = nil
}
